version: '3.3'

volumes:
  postgres_data:
  nginx:

services:
  db: # database server
    restart: always
    image: postgres:9.6.17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - variables.env
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "20"
  web: # django server
    restart: always
    image: my_web
    command: python3 manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "20"
    depends_on:
      - db
  nginx:
    restart: always
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ../build/:/usr/share/nginx/react_node
      - nginx:/etc/nginx/
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "20"
