# Generated by Django 2.2.9 on 2020-02-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolmentrequest',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='enrolmentrequest',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
