# Generated by Django 2.2.9 on 2020-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200228_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentrequest',
            name='approved',
            field=models.BooleanField(blank=True),
        ),
    ]
