# Generated by Django 2.2.9 on 2020-02-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200228_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentrequest',
            name='terms_confirmation',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
